version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
      POSTGRES_DB: mystore
    ports:
      - 5433:5432
    volumes:
    - database-data:/var/lib/postgresql/data/

volumes:
  database-data: